sudo: false
addons:
  apt:
    packages:
    - git
language: java
jdk: oraclejdk8
env: TERM=dumb
# don't build tags -- they would fail due to gradle-git anyway
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - git fetch --unshallow || true
  - git config user.email "tobias.schulte@gliderpilot.de"
  - git config user.name "Travis-CI"
  - git config url.https://.insteadOf git://
  - git checkout -qf $TRAVIS_BRANCH
# skip default gradlew assemble
install:
  - echo "skip default gradlew assemble"
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew release -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password --info --stacktrace || ./gradlew build --info --stacktrace'
